server:
  port: 8086
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
      - image/png
      - image/jpeg
      - image/jpg
spring:
  application:
    name: skill6-website
  datasource:
    username: username
    password: password
    url: url
    druid:
      name: skill6-mysql-01
    schema: classpath*:schema/*.sql
    initialization-mode: never
  redis:
    host: host
    password: password
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
dubbo:
  application:
    name: user-rbac-provider
  registry:
    address: zookeeper://localhost:2181
    username: username
    password: password
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: cn.skill6.common.entity.po
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    multiple-result-sets-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: cn.skill6.common.mybatis.GeneralStateFieldHandler
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    root: INFO
    cn.skill6.website.dao: DEBUG
    cn.skill6.website.config.SEOInterceptor: DEBUG
    cn.skill6.website.cache: DEBUG
    cn.skill6.website: INFO
    org.mybatis.spring: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%C::%M %L] %logger{15} - %msg%n'
skill6:
  file-path: /skill6/file/
  image-path: /skill6/image/
  sequence:
    worker:
      id: 1
    data-center:
      id: 1
  recaptcha:
    secret-key: key
    verify-url: https://www.recaptcha.net/recaptcha/api/siteverify
  github:
    client_id: gsasga241124
    client_secret: 1325dfd235dfs
    redirect_uri: https://127.0.0.1:8081/login/github
  qq:
    client_id: 123
    client_secret: 123
    redirect_uri: http://127.0.0.1:8081/login/qq
    scope: get_user_info,do_like
    state: skill-qq-login-test
shiro:
  loginUrl: /login/**
  successUrl: /
  unauthorizedUrl: /unauthorized
  config-path: classpath:config/shiro-urls.ini